version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  production:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "35:1e:5e:0a:95:ec:f3:3e:79:7b:b4:39:ac:00:5f:b2"
      - run: 
          name: update demo app on production server
          command: |
            ssh ubuntu@ssh.supertokens.io '\
              cd /home/ubuntu/supertokens-demo-react && \
              git checkout master && \
              git pull && \
              git checkout `git describe --match "[0-9]*" --abbrev=0 --tags $(git rev-list --tags --max-count=1)` && \
              rm package-lock.json && \
              npm i && \
              REACT_APP_API_PORT=10001 REACT_APP_API_URL=https://api-emailpassword.demo.supertokens.io REACT_APP_WEBSITE_PORT=10000 REACT_APP_WEBSITE_URL=https://emailpassword.demo.supertokens.io npm run build && \
              docker rm demo-app -f || true && \
              bash /home/ubuntu/supertokens-demo-react/scripts/start_container.sh'
      - slack/status
workflows:
  version: 2
  tagged-build:
    jobs:
      - production:
          filters:
            tags:
              only: /(\d\d\-\d\d\-\d\d\d\d\-\-\d\d\-\d\d\-\d\d)/
            branches:
              ignore: /.*/